apiVersion: v1
kind: ConfigMap
metadata:
 name: rvstore-api-gateway-config
 namespace: default
data:
 SPRING_PROFILES_ACTIVE: compose
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: rvstore-api-gateway
 labels:
  app: rvstore-api-gateway
spec:
 replicas: 2
 selector:
  matchLabels:
   app: rvstore-api-gateway
 template:
  metadata:
   labels:
    app: rvstore-api-gateway
  spec:
    containers:
    - name: rvstore-api-gateway
      image: "vergeops/k8s-rvstore-api-gateway:1.0"
      envFrom: 
      - configMapRef:
            name: rvstore-api-gateway-config
---
kind: Service
apiVersion: v1 
metadata:
    name: rvstore-api-gateway-service
spec:
    selector:
        app: rvstore-api-gateway
    ports:
    - protocol: TCP
    port: 9000
    nodePort: 30090
    type: NodePort
